# Site settings
title: FinlayLiu Blog
SEOTitle: 刘羽中的博客 | FinlayLiu Blog
header-img: img/home-bg.jpg
email: finlaylyz@gmail.com
description: "关于数据挖掘、机器学习和深度学习，与你一起发现更大的世界。"
keyword: "刘羽中，刘小水，FinlayLiu，机器学习，数据挖掘, 博客, 个人网站, 互联网"
url: "https://finlayliu.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: True
weibo_username:     liu873242298
zhihu_username:     finlayliu
github_username:    finlay-liu
twitter_username:   Finlay_Liu
#facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gem 'jekyll-paginate', group: :jekyll_plugins



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: finlayliu-com

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-109041237-1'            # Format: UA-xxxxxx-xx
ga_domain: finlayliu.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "风景只是背景，关键与谁同行。"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    #     title: "Su",
    #     href: "http://su.gallery/"
    {
        title: "Yong Yuan",
        href: "http://yongyuan.name/"
    },{
        title: "Rex Lee",
        href: "http://duguying.net/"
    }
]
